Creating full Book Database:

In [2]:
# import function
%load_ext autoreload
%autoreload 2
from functions import read_file, out_csv

yaml_path= "../config.yaml"
inp_data_section='raw_data'
file_name1= 'raw_scraped'    
file_name2= 'raw_api'    

#importing SMARD data file:
gr_df= read_file(yaml_path, inp_data_section, file_name1) #good reads books
ggl_df = read_file(yaml_path, inp_data_section, file_name2) #google books
display(gr_df.head(2))
display(ggl_df.head(2))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,book_name,book_url,source_list,author,rating,synopsis,pages,pub_date,genres,img_url
0,The Hunger Games,https://www.goodreads.com/book/show/2767052-th...,Best Books Ever,Suzanne Collins,4.35,Winning means fame and fortune. Losing means c...,374.0,2008-09-14,Young Adult|Dystopia|Fiction|Fantasy|Science F...,https://m.media-amazon.com/images/S/compressed...
1,Pride and Prejudice,https://www.goodreads.com/book/show/1885.Pride...,Best Books Ever,Jane Austen,4.30,This comedy of manners about the games of Eros...,279.0,1813-01-28,Classics|Romance|Fiction|Historical Fiction|Hi...,https://m.media-amazon.com/images/S/compressed...

,book_name,book_url,source_list,author,rating,synopsis,pages,pub_date,genres,img_url,data_source
0,Persuasion,https://play.google.com/store/books/details?id...,Best Books Ever,Jane Austen,NaN,Discover the timeless allure of love and secon...,260.0,2026-01-01,Fiction,http://books.google.com/books/content?id=UrrTE...,google_books
1,The Face of Another,http://books.google.de/books?id=_DYNAQAAMAAJ&d...,Best Books Ever,Kōbō Abe,NaN,The Japanese novelist Kobo Abe has often been ...,260.0,1992,Fiction,NaN,google_books